---
title: "ME2"
format: html
editor: visual
---

```{r}
#### Preamble ####
# Purpose: Get data on ticket and make a table for the average amount of tickets issued per day from 2014 to 2022
# Author: Denise Chang
# Email: ddleletan@hotmail.com
# Date: 14 January 2024

#### Workspace setup ####
library(knitr)
library(janitor)
library(lubridate)
library(opendatatoronto)
library(tidyverse)
library(usethis)
library(gitcreds)

use_git_config(
  user.name = "Denise Chang",
  user.email = "ddleletan@hotmail.com"
)
```

```{r}
#### Acquire ####
# from # https://open.toronto.ca/dataset/police-annual-statistical-report-tickets-issued/

toronto_tickets <-
  list_package_resources("police-annual-statistical-report-tickets-issued") |>
  filter(name == 
    "Tickets Issued.csv") |>
  get_resource()

write_csv(
  x = toronto_tickets,
  file = "toronto_tickets.csv"
)

# cleaning the data by extracting the number of tickets per offence year
toronto_tickets_clean <-
  clean_names(toronto_tickets)|>
  select(offence_year, ticket_count) |>
  group_by(offence_year) |>
  summarise(ticket_count = sum(ticket_count)) |>
  mutate(
    daily_avg_ticket_count = round((ticket_count / 365), 2)) |> 
  select(offence_year, daily_avg_ticket_count)

# head(toronto_tickets_clean)

write_csv(
  x = toronto_tickets_clean,
  file = "cleaned_toronto_tickets.csv"
)
```

```{r}
#### Explore ####
toronto_tickets_clean <-
  read_csv(
    "cleaned_toronto_tickets.csv",
    show_col_types = FALSE
  )

toronto_tickets_clean |>
  kable(
    col.names = c("Year", "Average daily number of tickets issued"),
    digits = 1
  )
```
